# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230)),
                ('body', models.TextField()),
                ('dR', models.DateTimeField()),
            ],
        ),
    ]
